### ISSUE TITLE
Webpack 4 support

### ISSUE THREAD

**Issue by igor-savin-ht** [alleyinteractive/sasslint-webpack-plugin#33]
1.0.4

After update to Webpack 4 this plugin begins to crash with

```
C:\sources\crm-frontend\node_modules\sasslint-webpack-plugin\index.js:47
          _this.warnings.push(x.file);
                         ^

TypeError: Cannot read property 'push' of undefined
    at C:\sources\crm-frontend\node_modules\sasslint-webpack-plugin\index.js:47:26
    at Array.forEach (<anonymous>)
    at C:\sources\crm-frontend\node_modules\sasslint-webpack-plugin\index.js:43:14
    at SyncHook.eval [as call] (eval at create (C:\sources\crm-frontend\node_modules\tapable\lib\HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (C:\sources\crm-frontend\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\sources\crm-frontend\node_modules\webpack\lib\Compilation.js:826:19)
    at hooks.make.callAsync.err (C:\sources\crm-frontend\node_modules\webpack\lib\Compiler.js:464:17)
    at _err0 (eval at create (C:\sources\crm-frontend\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (C:\sources\crm-frontend\node_modules\webpack\lib\Compilation.js:749:12)
    at processModuleDependencies.err (C:\sources\crm-frontend\node_modules\webpack\lib\Compilation.js:688:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```

**Comment by mevbg** [comment]
+1

**Comment by ChristianGrete** [comment]
Same here with errors:

```
./node_modules/sasslint-webpack-plugin/index.js:45
          _this.errors.push(x.file);
                       ^

TypeError: Cannot read property 'push' of undefined
```

**Comment by MustardForBreakfast** [comment]
+1 for visibility

**Comment by MustardForBreakfast** [comment]
For the time being, you can run `sass-lint` via the cli and use [`webpack-shell-plugin`](https://www.npmjs.com/package/webpack-shell-plugin) to incorporate it into your webpack builds until this plugin is fixed.

In `package.json`:
```
"scripts": {
    "lint-style": "sass-lint -c .sass-lint.yml 'src/**/*.scss' -v -q",
 },
```

In `webpack.config`:

```
const WebpackShellPlugin = require('webpack-shell-plugin');
 ...
  plugins: [
      new WebpackShellPlugin({
          onBuildStart: ['yarn lint-style'],
          dev: false,
    }),
  ],
```

**Comment by swordray** [comment]
Guys, I wrote a plugin for Webpack 4. Try it out at https://github.com/swordray/sass-lint-webpack.

**Comment by ndrau** [comment]
Guys, I still get the error. Any news on a fix?

**Comment by jeromefaria** [comment]
+1 for visibility as it is still happening on my system.
